import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto_Mono } from "next/font/google";

const RobotoMono = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={RobotoMono.className}>{children}</body>
    </html>
  );
}
